import { CarportConfig } from '../types/carport';

export const PRESETS: { id: string; name: string; tag: string; description: string; config: Partial<CarportConfig> }[] = [
  {
    id: 'pro-single-louver',
    name: 'Carport Modern Pro 1-Stanowiskowy',
    tag: 'Bestseller',
    description: 'Pojedyncza wiata z ruchomymi lamelami bioklimatycznymi, żaluzją drewnianą i stacją Wallbox 22kW.',
    config: {
      name: 'Carport Modern Pro (1 Auto)',
      installationType: 'freestanding',
      bays: 1,
      dimensions: {
        width: 3.6,
        length: 5.8,
        height: 2.45,
        slope: 0,
      },
      postProfile: '150x150',
      roofType: 'bioclimatic',
      louverAngle: 45,
      sideWalls: {
        left: 'wood-slats',
        right: 'none',
        back: 'none',
      },
      storageRoom: {
        enabled: false,
        depth: 1.5,
        hasWindow: false,
      },
      colors: {
        frameRal: 'RAL 7016',
        frameName: 'Antracytowy Szary',
        frameHex: '#373F43',
        roofRal: 'RAL 7016',
        roofName: 'Antracytowy Szary',
        roofHex: '#373F43',
        woodTone: 'oak',
      },
      accessories: {
        ledPerimeter: true,
        ledLouvers: true,
        ledBrightness: 85,
        ledColorTemp: 'warm',
        evCharger: true,
        gutterSystem: true,
        infraredHeater: false,
        somfyMotor: true,
        weatherSensor: true,
      },
      environment: {
        showCar: true,
        carType: 'ev',
        showWall: false,
        groundType: 'pavers',
        timeOfDay: 'day',
        showDimensions: true,
        viewAngle: 'perspective',
      },
    },
  },
  {
    id: 'double-luxury-storage',
    name: 'Carport Double Luxury ze Schowkiem',
    tag: 'Kompleksowy',
    description: 'Szeroka wiata na dwa duże auta (SUV/kombi) ze zintegrowanym schowkiem rowerowo-narzędziowym.',
    config: {
      name: 'Carport Double ze Schowkiem',
      installationType: 'freestanding',
      bays: 2,
      dimensions: {
        width: 6.2,
        length: 7.2,
        height: 2.6,
        slope: 0,
      },
      postProfile: '200x200',
      roofType: 'bioclimatic',
      louverAngle: 60,
      sideWalls: {
        left: 'wood-slats',
        right: 'alu-shutters',
        back: 'solid-panel',
      },
      storageRoom: {
        enabled: true,
        depth: 1.8,
        hasWindow: false,
      },
      colors: {
        frameRal: 'RAL 7016',
        frameName: 'Antracytowy Szary',
        frameHex: '#373F43',
        roofRal: 'RAL 9010',
        roofName: 'Biel Alpejska (Kontrast)',
        roofHex: '#F7F9F9',
        woodTone: 'larch',
      },
      accessories: {
        ledPerimeter: true,
        ledLouvers: true,
        ledBrightness: 100,
        ledColorTemp: 'neutral',
        evCharger: true,
        gutterSystem: true,
        infraredHeater: true,
        somfyMotor: true,
        weatherSensor: true,
      },
      environment: {
        showCar: true,
        carType: 'suv',
        showWall: false,
        groundType: 'concrete',
        timeOfDay: 'day',
        showDimensions: true,
        viewAngle: 'perspective',
      },
    },
  },
  {
    id: 'bipv-solar-eco',
    name: 'Carport Solar BIPV Eco Energy',
    tag: 'Samowystarczalny',
    description: 'Dach z bezpiecznych modułów fotowoltaicznych BIPV generujących prąd bezpośrednio do domowego Wallboxa.',
    config: {
      name: 'Carport Solar BIPV',
      installationType: 'freestanding',
      bays: 2,
      dimensions: {
        width: 5.8,
        length: 6.0,
        height: 2.5,
        slope: 5,
      },
      postProfile: '200x200',
      roofType: 'solar',
      louverAngle: 0,
      sideWalls: {
        left: 'alu-shutters',
        right: 'none',
        back: 'wood-slats',
      },
      storageRoom: {
        enabled: false,
        depth: 1.5,
        hasWindow: false,
      },
      colors: {
        frameRal: 'RAL 9005',
        frameName: 'Głęboka Czerń',
        frameHex: '#1C1D21',
        roofRal: 'RAL 9005',
        roofName: 'Głęboka Czerń',
        roofHex: '#1C1D21',
        woodTone: 'walnut',
      },
      accessories: {
        ledPerimeter: true,
        ledLouvers: false,
        ledBrightness: 90,
        ledColorTemp: 'cold',
        evCharger: true,
        gutterSystem: true,
        infraredHeater: false,
        somfyMotor: false,
        weatherSensor: true,
      },
      environment: {
        showCar: true,
        carType: 'ev',
        showWall: false,
        groundType: 'pavers',
        timeOfDay: 'day',
        showDimensions: true,
        viewAngle: 'perspective',
      },
    },
  },
  {
    id: 'attached-glass-modern',
    name: 'Pergola Przyścienna Szklana Modern',
    tag: 'Przyścienna',
    description: 'Montaż do elewacji budynku, lekkie zadaszenie ze szkła hartowanego VSG i ciepłe oświetlenie obwodowe LED.',
    config: {
      name: 'Pergola Przyścienna Glass',
      installationType: 'attached',
      bays: 1,
      dimensions: {
        width: 3.8,
        length: 5.5,
        height: 2.4,
        slope: 3,
      },
      postProfile: '150x150',
      roofType: 'glass',
      louverAngle: 0,
      sideWalls: {
        left: 'glass-sliding',
        right: 'none',
        back: 'none',
      },
      storageRoom: {
        enabled: false,
        depth: 1.4,
        hasWindow: false,
      },
      colors: {
        frameRal: 'RAL 7016',
        frameName: 'Antracytowy Szary',
        frameHex: '#373F43',
        roofRal: 'RAL 7016',
        roofName: 'Antracytowy Szary',
        roofHex: '#373F43',
        woodTone: 'oak',
      },
      accessories: {
        ledPerimeter: true,
        ledLouvers: false,
        ledBrightness: 80,
        ledColorTemp: 'warm',
        evCharger: true,
        gutterSystem: true,
        infraredHeater: true,
        somfyMotor: false,
        weatherSensor: false,
      },
      environment: {
        showCar: true,
        carType: 'sedan',
        showWall: true,
        groundType: 'pavers',
        timeOfDay: 'sunset',
        showDimensions: true,
        viewAngle: 'perspective',
      },
    },
  },
];

export const DEFAULT_CONFIG: CarportConfig = {
  id: 'custom-carport-01',
  name: 'Indywidualna Pergola Garażowa',
  installationType: 'freestanding',
  bays: 1,
  dimensions: {
    width: 3.8,
    length: 6.0,
    height: 2.5,
    slope: 0,
  },
  postProfile: '150x150',
  roofType: 'bioclimatic',
  louverAngle: 45,
  louverAnimation: false,
  sideWalls: {
    left: 'wood-slats',
    right: 'none',
    back: 'none',
  },
  storageRoom: {
    enabled: false,
    depth: 1.6,
    hasWindow: false,
  },
  colors: {
    frameRal: 'RAL 7016',
    frameName: 'Antracytowy Szary',
    frameHex: '#373F43',
    roofRal: 'RAL 7016',
    roofName: 'Antracytowy Szary',
    roofHex: '#373F43',
    woodTone: 'oak',
  },
  accessories: {
    ledPerimeter: true,
    ledLouvers: true,
    ledBrightness: 85,
    ledColorTemp: 'warm',
    evCharger: true,
    gutterSystem: true,
    infraredHeater: false,
    somfyMotor: true,
    weatherSensor: true,
  },
  environment: {
    showCar: true,
    carType: 'suv',
    showWall: false,
    groundType: 'pavers',
    timeOfDay: 'day',
    showDimensions: true,
    viewAngle: 'perspective',
  },
  project: {
    projectName: 'Pergola Garażowa Rezydencjalna',
    investorName: 'Inwestor Prywatny',
    investmentAddress: 'ul. Parkowa 12, Warszawa',
    plotNumber: '142/5 obr. 0012',
    designerName: 'Studio Architektury Krajobrazu',
    notes: 'Zasilanie 400V doprowadzone do słupa lewego przedniego pod stację Wallbox. Fundamenty punktowe pod stopy.',
    creationDate: '2026-09-26',
    discountPercent: 0,
    customUnitMultiplier: 1.0,
  },
  customCostItems: [],
};
